version: '3'
services:
  experiment_manager:
    environment:
      DISABLE_CONTRACTS: 1
      AIDONODE_ENCODING: cbor
    build:
      context: ./experiment_manager
    volumes: &volumes
      - ./challenges-dir:/challenges
      - fifos:/fifos

  predictor:
    build:
      context: ./predictor_random
    environment:
      AIDONODE_DATA_IN: /fifos/predictor-in
      AIDONODE_DATA_OUT: fifo:/fifos/predictor-out
      AIDONODE_ENCODING: cbor
    volumes: *volumes
volumes:
  fifos:
